[[stork]]
arch = "aarch64"
git-tree-sha1 = "e71a176c3ad1160ecfc378882345ab88c3894b21"
libc = "glibc"
os = "linux"

    [[stork.download]]
    sha256 = "6fcafa494a657b00ed342d6a410eb86ffca11e8953afa8699e2f3118f5accb34"
    url = "https://github.com/JuliaBinaryWrappers/stork_jll.jl/releases/download/stork-v1.6.0+0/stork.v1.6.0.aarch64-linux-gnu.tar.gz"
[[stork]]
arch = "aarch64"
git-tree-sha1 = "b9b125ceca0820494e21b0a6605f0c1a12888c96"
libc = "musl"
os = "linux"

    [[stork.download]]
    sha256 = "d7bd5f9746fe26c49b22f8409cf414efc211248c48125262758d36da1c1b699c"
    url = "https://github.com/JuliaBinaryWrappers/stork_jll.jl/releases/download/stork-v1.6.0+0/stork.v1.6.0.aarch64-linux-musl.tar.gz"
[[stork]]
arch = "powerpc64le"
git-tree-sha1 = "3203257f67777b470d68ec6e148fcc4e0fba72fd"
libc = "glibc"
os = "linux"

    [[stork.download]]
    sha256 = "c5a61f15a6e189e0fe6b9cfb9ce0a18c4721cb42162d3cfd71fe21868f4fa66b"
    url = "https://github.com/JuliaBinaryWrappers/stork_jll.jl/releases/download/stork-v1.6.0+0/stork.v1.6.0.powerpc64le-linux-gnu.tar.gz"
[[stork]]
arch = "x86_64"
git-tree-sha1 = "685b227c0ba3ee1895b2a0ad8b6325fc62ffe8d5"
libc = "glibc"
os = "linux"

    [[stork.download]]
    sha256 = "79d468b87dc1e85e2b3383c0d1300088c3daa6cacd658612e39f595668a42786"
    url = "https://github.com/JuliaBinaryWrappers/stork_jll.jl/releases/download/stork-v1.6.0+0/stork.v1.6.0.x86_64-linux-gnu.tar.gz"
[[stork]]
arch = "x86_64"
git-tree-sha1 = "162bed4645ec393dcaf98cb3551428a2ed04b0f1"
libc = "musl"
os = "linux"

    [[stork.download]]
    sha256 = "43a27c3b7e9b981baeff946e3303dcb5986d8b61afe1436f30177c4985305678"
    url = "https://github.com/JuliaBinaryWrappers/stork_jll.jl/releases/download/stork-v1.6.0+0/stork.v1.6.0.x86_64-linux-musl.tar.gz"
