# Autogenerated wrapper script for stork_jll for x86_64-linux-gnu
export stork

using OpenSSL_jll
JLLWrappers.@generate_wrapper_header("stork")
JLLWrappers.@declare_executable_product(stork)
function __init__()
    JLLWrappers.@generate_init_header(OpenSSL_jll)
    JLLWrappers.@init_executable_product(
        stork,
        "bin/stork",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
